4modul
js-tasks-ru/jsbasic-20200727_prey122 pull request #6
Opened 2020-08-20 20:53 UTC by trashmarket

2020-08-20 21:00 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция makeFriendsList(friends)
+ функция должна возвращать HTML список
+ проверяем содержимое списка
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-08-21 11:53 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-08-21 17:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку первой строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
```
```diff
Функция makeFriendsList(friends)
+ функция должна возвращать HTML список
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ проверяем содержимое списка
```
```diff
Функция highlight
- Проставит аттрибут hidden, если  data-available атрибута нет вообще
- Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
- Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
- Проставит класс male/female, в зависимости от содержимого ячекйки Gender
```

2020-08-26 19:48 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-08-26 20:56 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-08-27 07:03 UTC, dolgachio commented on 4-module/1-task/index.js
> +  let div
Только переменную лучше назвать не div, а как-то иначе. Это немного сбивает с толку

2020-08-27 07:03 UTC, dolgachio commented on 5-module/1-task/index.js
> +  document.querySelector('.hide-self-button').addEventListener("click", function(){
👍

2020-08-27 07:03 UTC, dolgachio commented on 4-module/3-task/index.js
> +    for(let i = 0; i < table.rows.length; i++){
👍  спасибо, что внесли изменения

2020-08-27 07:03 UTC, dolgachio commented on 5-module/2-task/index.js
> +  document.querySelector('.toggle-text-button').addEventListener('click', function(){
👍

2020-08-27 07:04 UTC, stas-dolgachov approved these changes

2020-08-27 07:04 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-08-28 08:54 UTC, stas-dolgachov requested changes

2020-08-28 08:54 UTC, stas-dolgachov commented on 4-module/3-task/index.js
> +                console.log(table.rows[i]);
Удалите, пожалуйста, console.log

2020-08-28 11:08 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-08-28 13:11 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-08-29 10:26 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-08-29 11:55 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-08-30 08:37 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-08-30 09:41 UTC, stas-dolgachov commented on 5-module/3-task/index.js
> +  console.log(width);
Вот тут еще удалите, пожалуйста.

2020-08-30 09:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @stas-dolgachov

2020-08-30 10:11 UTC, stas-dolgachov approved these changes
👍  Вы молодец и проделали отличную работу!

2020-08-30 10:12 UTC, merged