6modul 3task
js-tasks-ru/jsbasic-20200727_prey122 pull request #8
Opened 2020-09-03 12:19 UTC by trashmarket

2020-09-03 12:26 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 6-module/3-task/task.test.js — добавлен
```

2020-09-03 21:24 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 6-module/3-task/task.test.js — добавлен
```

2020-09-04 07:10 UTC, stas-dolgachov approved these changes

2020-09-04 07:10 UTC, stas-dolgachov commented on 6-module/3-task/index.js
> +export default class Carousel {
👍

2020-09-04 07:10 UTC, stas-dolgachov commented on 6-module/3-task/index.js
> +      //this.arrowLeft.style.display = 'none';
Общая рекомендация удалять закомментированный код

2020-09-04 07:10 UTC, stas-dolgachov commented on 6-module/3-task/index.js
> +     // console.log(this.countId);
Общая рекомендация удалять закомментированный код

2020-09-04 07:10 UTC, stas-dolgachov commented on 6-module/3-task/index.js
> +       // console.log(this.width);
Общая рекомендация удалять закомментированный код

2020-09-04 07:10 UTC, stas-dolgachov commented on 6-module/3-task/index.js
> +    //console.log(this.width );
Общая рекомендация удалять закомментированный код

2020-09-04 07:11 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-09-05 19:19 UTC, stas-dolgachov requested changes

2020-09-05 19:19 UTC, stas-dolgachov commented on 6-module/3-task/index.js
> +    this.elem.addEventListener('product-add', (event) => console.log(event.detail));
Удалите, пожалуйста, этот обработчик

2020-09-09 11:55 UTC, dolgachio commented on 6-module/3-task/index.js
> +    this.elem.addEventListener('product-add', (event) => console.log(event.detail));
Удалите, пожалуйста, этот обработчик @trashmarket

2020-09-14 17:22 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Учебный проект: Карусель
+ в исходном состоянии скрывает стрелку переключения назад
+ при достижении крайнего слайда, должна скрыть стрелку переключения вперёд
+ при клике по кнопке "назад", должна переключать на один слайд назад
+ при клике по кнопке "вперёд", должна переключать на один слайд вперёд
+ должна добавлять корневой элемент в свойство "elem"
+ должна отрисовать все слайды
+ после клика по кнопке, должно быть создано событие
+ созданное событие должно содержать в себе уникальный идентификатор товара("id") c 1-ого слайда
```
```diff
Учебный проект: Лента-Меню
+ после клика по ссылке, должно быть создано событие
+ созданное событие должно содержать в себе уникальный идентификатор товара ("id")
+ должна добавлять корневой элемент в свойство "elem"
+ должна отрисовать все категории
+ при клике по кнопке "назад", должна прокрутить на 350px назад
+ при клике на кнопке "вперёд", должна прокрутить на 350px вперёд
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-09-17 08:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @stas-dolgachov

2020-09-21 11:27 UTC, stas-dolgachov approved these changes

2020-09-21 11:27 UTC, merged